services:
  php:
    build: .
    container_name: php
    env_file: ./src/.env
    volumes:
      - ./src:/app
    expose:
      - "9000"
    networks:
      - camagru-net
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - camagru-net
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: ./src/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - camagru-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"   # SMTP port
      - "8025:8025"   # Web UI
    networks:
      - camagru-net

volumes:
  mysql_data:

networks:
  camagru-net:
    driver: bridge